# Generated by Django 3.1.7 on 2021-03-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0002_auto_20210329_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
