# Generated by Django 3.1.7 on 2021-03-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0003_auto_20210329_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country_code',
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
