# Generated by Django 3.1.7 on 2021-03-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0006_auto_20210330_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator',
            new_name='maker',
        ),
    ]
