# Generated by Django 3.1.7 on 2021-03-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0007_auto_20210330_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AU', 'Author'), ('MA', 'Maker')], default='AU', max_length=2),
        ),
    ]
